name: Long Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: create dir
        run: |
          mkdir output  # create output dir

      - name: Make PDF
        uses: docker://pandoc/latex:3.5
        with:
          args: >-  # allows you to break string into multiple lines
            -s
            -H margins.sty
            --bibliography mendeley.bib
            --csl plos.csl
            --metadata title="David Pierson Bradway, Ph.D."
            --citeproc
            -o output/resume.pdf
            resume_with_citations.md

      - name: Make TeX
        uses: docker://pandoc/latex:3.5
        with:
          args: >-  # allows you to break string into multiple lines
            -s
            -H margins.sty
            --bibliography mendeley.bib
            --csl plos.csl
            --metadata title="David Pierson Bradway, Ph.D."
            --citeproc
            -o output/resume.tex
            resume_with_citations.md

      - name: Make Word Doc
        uses: docker://pandoc/latex:3.5
        with:
          args: >-  # allows you to break string into multiple lines
            -s
            -H margins.sty
            --bibliography mendeley.bib
            --csl plos.csl
            --metadata title="David Pierson Bradway, Ph.D."
            --citeproc
            -o output/resume.docx
            resume_with_citations.md

      - name: Make HTML page
        uses: docker://pandoc/latex:3.5
        with:
          args: >-  # allows you to break string into multiple lines
            -s
            --bibliography mendeley.bib
            --csl plos.csl
            --metadata title="David Pierson Bradway, Ph.D."
            --citeproc
            -o output/resume.html
            resume_with_citations.md

      - name: Make ReST file
        uses: docker://pandoc/latex:3.5
        with:
          args: >-  # allows you to break string into multiple lines
            -s
            -t rst
            --bibliography mendeley.bib
            --csl plos.csl
            --metadata title="David Pierson Bradway, Ph.D."
            --citeproc
            -o output/resume.rst
            resume_with_citations.md

      - name: Publish files
        uses: actions/upload-artifact@v4
        with:
          name: resume
          path: output
